# https://docs.travis-ci.com/user/job-lifecycle/
language: node_js

node_js:
  - 12

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.cache/yarn
    - ~/.cache/Cypress
  # install dependencies
  override:
    - yarn

# check that Cypress can run
before_script:
  # just in case the install script skipped Cypress post-install hook for some reason
  # call install ourselves. If there is binary already installed, it will quickly finish
  - yarn cypress install
  # where is Cypress binary cached?
  - yarn cypress cache path
  # show me all versions of Cypress binary cached
  - yarn cypress cache list
  - yarn cypress verify

script:
  - yarn cypress version
