# https://docs.travis-ci.com/user/job-lifecycle/
language: node_js

node_js:
  - 12

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.cache/yarn
    - ~/.cache/Cypress

install:
  # install dependencies
  - yarn install --frozen-lockfile
  # just in case the install script skipped Cypress post-install hook for some reason
  # call install ourselves. If there is binary already installed, it will quickly finish.
  # By overriding the install step we make sure the NPM modules AND the Cypress binary
  # are installed before the cache is saved
  - yarn cypress install
  # good idea to verify the binary so its status is saved in the cache as well
  - yarn cypress verify

# check that Cypress can run
before_script:
  # where is Cypress binary cached?
  - yarn cypress cache path
  # show me all versions of Cypress binary cached
  - yarn cypress cache list

script:
  - yarn cypress version
